docker-compose.yml, hydrus/app.py, hydrus/data/crud.py, hydrus/data/doc_parse.py, hydrus/data/insert_classes.py, hydrus/hydraspec/doc_writer.py, hydrus/metadata/drone_doc_gen.py, hydrus/metadata/server_doc_gen.py, hydrus/tests/test_app.py, hydrus/tests/test_crud.py
- Server bug fixed, now working with hydra console
- Tests updated
#will finish drone once we finalize the design.
=> Server bug fix

hydrus/app.py, hydrus/data/crud.py, hydrus/data/exceptions.py, hydrus/tests/test_app.py, hydrus/tests/test_crud.py
Added new exceptions in the DB responses, no HTTP responses in the `crud.py` file anymore.
Made custom exceptions.
Made changes to the app to use the new operations
Updated tests for the app, all passing
Solves: #55 
Todo:
Update `test_crud.py`
=> New exceptions in DB layer, all HTTP responses in views

hydrus/data/crud.py
- Bug fix in id generation of objects, everything working fine now
=> Bug fix in hydrus crud

hydrus/utils.py
Fixing the tests and server issues
=> Fix tests.

.github/CODE_OF_CONDUCT.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
fixes #85 
I have added template for issue and pull request.
=> template for issue and pull request added

.github/CONTRIBUTING.md
Fixes #94 
I have added CONTRIBUTING.md file
=> contributing guide added

main.py
Fixes #103 
The server url in now displayed in the output of main.py. Now the user can click it directly rather than typing it in the URL bar.
=> feat: Display server URL in output of main.py 

.github/ISSUE_TEMPLATE.md
=> Update Issue_Template(fix typo)

.gitignore, hydrus/app.py, hydrus/hydraspec/doc_maker.py, hydrus/tests/test_app.py, hydrus/tests/test_auth.py, main.py
Fixes: #79
Signed-off-by: Yash Ladha <yashladhapankajladha123@gmail.com>
(cherry picked from commit ccd42a0)
Signed-off-by: Yash Ladha <yashladhapankajladha123@gmail.com>
Changes the code to follow pep-8 convention.
=> Fixed the Code according to Conventions (PEP-8).

.github/PULL_REQUEST_TEMPLATE.md
Fixes #
NA
Add test logs section to PR template
=> Add test logs section to PR template

hydrus/app.py, hydrus/hydraspec/doc_maker.py
Fixes #128
Add mypy type annotations in app.py and doc_maker.py
=> Add type annotations

hydrus/tests/test_app.py, hydrus/tests/test_auth.py
Fixes #129  
The `hydrus` utilities were being set up and destroyed for each test function. To prevent this, I am setting up utilities in the `setUpClass`, using them for all the tests and then destroying them in the `tearDownClass`. To achieve this, I have used the implicit  `__enter__()` and `__exit__()` methods of the `contextmanager` decorator.
=> revamp tests

hydrus/utils.py
Fixes #98 
- My branch is up-to-date with upstream/develop branch.
- Everything works and tested for Python 3.5.2 and above.
*Checking only for scoped_session in set_session()*
```
 b@man  ~/gitpository/hydrus   docmaster  python3 -m unittest hydrus/tests/test_app.py
Creating a temporary database...
Classes and properties added successfully.
Setting up Hydrus utilities... 
Creating utilities context... 
Setup done, running tests...
...............
----------------------------------------------------------------------
Ran 15 tests in 0.111s
OK
 b@man  ~/gitpository/hydrus   docmaster  python3 -m unittest hydrus/tests/test_auth.py
Creating a temporary datatbase...
Classes, Properties and Users added successfully.
Setting up Hydrus utilities... 
Creating utilities context... 
Setup …
```
=> Improved documentation on utils.py. 

hydrus/app.py
Before : Object with ID %s successfully deleted
After : Object with ID %s successfully added
=> Changed Item insertion message in app.py

hydrus/utils.py
Fixes #98 
As it turns out, some of the changes I intended to add in #138 got lost in merges.
Raising another PR to incorporate the same.
- My branch is up-to-date with upstream/develop branch.
- Everything works and tested for Python 3.5.2 and above.
- Reordered getters and setters to the order of their call in main.py
*Checking only for scoped_session in set_session()*
```
 b@man  ~/gitpository/hydrus   docmaster  python3 -m unittest hydrus/tests/test_app.py
Creating a temporary database...
Classes and properties added successfully.
Setting up Hydrus utilities... 
Creating utilities context... 
Setup done, running tests...
...............
----------------------------------------------------------------------
Ran 15 tests in 0.111s
OK
 b@man  ~/gitpository/hydrus   docmaster  …
```
=>  Improved documentation on utils.py. Upgrade on PR#138 

hydrus/tests/test_auth.py
Fixes #140 
I have added tests for Invalid User and Invalid Password. Please review them and please tell, other cases for which we have to add tests in test_auth.py.
=> Tests added for Invalid User and Invalid Password

setup.py
Fixes : #102
Signed-off-by: Yash Ladha <yashladhapankajladha123@gmail.com>
Formatted setup file to use setuptools.
=> Fixed the setup file for installation and setup for correct dependencies

hydrus/app.py
fixes #98 . Added documentation for app.py 
adds documentation to app.py
=> added documentation for app.py. WIP

hydrus/app.py
Improves on #98 
```
 b@man  ~/gitpository/hydrus   docmaster_dos ✚  python3 -m unittest hydrus/tests/test_auth.py
Creating a temporary datatbase...
Classes, Properties and Users added successfully.
Setting up Hydrus utilities... 
Creating utilities context... 
Setup done, running tests...
........
----------------------------------------------------------------------
Ran 8 tests in 0.046s
OK
 b@man  ~/gitpository/hydrus   docmaster_dos ✚  python3 -m unittest hydrus/tests/test_app.py 
Creating a temporary database...
Classes and properties added successfully.
Setting up Hydrus utilities... 
Creating utilities context... 
Setup done, running tests...
...............
----------------------------------------------------------------------
Ran 15 tests in 0.112s
OK
 b@man  …
```
=> Added documentation to Item and ItemCollection in app.py

hydrus/data/crud.py, hydrus/data/doc_parse.py, hydrus/utils.py, main.py
Fixes #99 
Previously the utils.py only moved from ```Session``` to ```scoped_session``` while checking for the kind of session being used by the user would be more accurate according to me. Also porting to scoped_session was ignored in some files like crud.py and doc_parse.py. These changes aim to complete the porting process to scoped_session across the whole project.
```bash
Creating a temporary database...
Classes and properties added successfully.
Setting up Hydrus utilities...
Creating utilities context...
Setup done, running tests...
...............Creating a temporary datatbase...
Classes, Properties and Users added successfully.
Setting up Hydrus utilities...
Creating utilities context...
Setup done, running tests...
........Creating a temporary datatbsse...
Classes and …
```
=> included scoped_session for crud.py, utils.py, doc_parse.py

.vscode/settings.json, hydrus/data/crud.py
Fixes #98
- [ X] My branch is up-to-date with upstream/develop branch.
- [ X] Everything works and tested for Python 3.5.2 and above.
Adds documentation for imports in crud.py .
=>  added documentation for imports in crud.py

cli.py, hydrus/utils.py
Fixes #184 
Fixes #185 
Removes redundant declaration of get_authentication method and replace if-else block with more efficient try except block
```
============================= test session starts ==============================
platform linux -- Python 3.5.2, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/vishal/oss/hydrus, inifile:
collected 35 items                                                             
hydrus/tests/test_app.py ...............                                 [ 42%]
hydrus/tests/test_auth.py ..........                                     [ 71%]
hydrus/tests/test_crud.py ..........                                     [100%]
========================== 35 passed in 3.18 seconds ===========================
```
=> Changed if-else block with try-except block in utils.py

requirements.txt
=> Fixed Double requirement given for Click

hydrus/hydraspec/doc_writer_sample.py, hydrus/hydraspec/doc_writer_sample_output.py, setup.py
- Update setup.py for pip >= 10 and backward compatibility
- Update doc_writer_sample.py
=> Update setup.py and doc_writer_sample.py

doc.jsonld
- [ X] My branch is up-to-date with upstream/develop branch.
- [ X] Everything works and tested for Python 3.5.2 and above.
=> updated doc.jsonld with Method PUT for /areaa

requirements.txt
Fixes #217 
Updated the packages Flask , Jinja2 and Werkzeug .
=> Updated Flask

hydrus/app.py, hydrus/data/crud.py
Fixes #219 
PR modifes the "@id" and "@context" according to custom path if provided
=> Perfecting custom endpoint mechanism 

hydrus/app.py, hydrus/data/crud.py, hydrus/tests/test_app.py, hydrus/tests/test_crud.py
Fixes #200 
It allows us to add , update , delete multiple objects in a single request by allowing arrays to be accepted as inputs .
=> Implementing arrays as inputs parameters 

hydrus/parser/openapi_parser.py, hydrus/tests/test_parser.py
Fixes #207 
- [X ] Everything works and tested for Python 3.5.2 and above.
Unittests for parser
=> Tests for parser 

hydrus/tests/test_crud.py
Fixes #240 
Synchronised the way of importing the docs in all tests
=> Update the method of importing doc in test_crud

cli.py
Fixes #254 
- [ x ] My branch is up-to-date with upstream/develop branch.
- [ x ] Everything works and tested for Python 3.5.2 and above.
- Replaced the use of deprecated `gevent.wsgi` with `gevent.pywsgi`
- Import Error
- Deprecated feature 1
=> Replace the use of deprecated gevent.wsgi with gevent.pywsgi

cli.py
Fixes #256 
Creates a CLI command for parser , user has to use `-o` flag and supply location of open api doc , the command parses the open api doc at location , creates a hydra doc and starts a server for the hydra doc .
=> Cli command for parser 

cli.py
=> Revert "Cli command for parser "

hydrus/app.py
=> Fixes data base errors on collections using UUID

hydrus/parser/openapi_parser.py, hydrus/tests/test_parser.py
=> Tests parser

hydrus/data/doc_parse.py
Fixes #
Updates the doc string.
- Feature 1
- Feature 2
- Change 1
- Change 2
- Bug 1
- Deprecated feature 1
=> Correct documentation in doc_parse.py

cli.py, hydrus/parser/openapi_parser.py
- Refactor openapi_parse to separate the dumping mechanism,
- Now using --hydradoc for both openapi and hydra doc files,
- Improve cli not hydrus serve can be used from anywhere,
- Made cli.py PEP8 compliant
=> Cli.py improvements done

hydrus/tests/test_parser.py
=> Fixed parser tests and removed relative file imports

hydrus/tests/test_crud.py
Fixes #293 
- [ x ] My branch is up-to-date with upstream/develop branch.
- [ x ] Everything works and tested for Python 3.5.2 and above.
```
platform linux -- Python 3.5.2, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/vishal/oss/hydrus, inifile:
collected 51 items                                                                                                                          
hydrus/tests/test_app.py ................                                                                                             [ 31%]
hydrus/tests/test_auth.py ..........                                                                                                  [ 50%]
hydrus/tests/test_crud.py ............ …
```
=> Debug test code fop update functionality

hydrus/app.py
Fixes #297 
Adapt `Context` in app.py to return endpoint classes with independent paths.
```
(h) vishal@vishal:~/oss/hydrus$ pytest hydrus/tests
============================================================ test session starts ============================================================
platform linux -- Python 3.5.2, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/vishal/oss/hydrus, inifile:
collected 51 items                                                                                                                          
hydrus/tests/test_app.py ................                                                                                             [ 31%]
hydrus/tests/test_auth.py .......... …
```
=> Adapt Context to work with endpoint classes with independent paths

.travis.yaml
=> Add travis to hydrus

hydrus/data/db_models.py
Fixes #216 
```
========================== test session starts ===========================
platform linux -- Python 3.6.7, pytest-4.0.2, py-1.7.0, pluggy-0.8.0
rootdir: /home/invinciblycool/Documents/Github-projects/hydrus, inifile:
collected 51 items                                                       
hydrus/tests/test_app.py ................                          [ 31%]
hydrus/tests/test_auth.py ..........                               [ 50%]
hydrus/tests/test_crud.py ............                             [ 74%]
hydrus/tests/test_doc_writer.py ....                               [ 82%]
hydrus/tests/test_parser.py .........                              [100%]
======================= 51 passed in 1.15 seconds ========================
```
=> Add created and last_modified fields

.vscode/settings.json
Fixes #303 and #324 
Made changes to delete the contents of .vscode, the settings folder for VSCode.
Deleted VSCode settings.json file
=> REMOVED VSCode settings.json file

cli.py
This is a quick fix that solves a single typo in the file cli.py
Fixes #363 
The errors caused by the wrong import statement in cli.py is deeply regretted and is solved in this PR
=> Correct typo in import

hydrus/tests/test_crud.py, tests/test_cli.py
=> added test for cli.py

cli.py, hydrus/samples/hydra_doc_sample.py
Fixes #
- Incorrect load of Hydra Documentation 
- Update demo api document 
- Update cli message with the correct path 
Some wrong configuration found on hydrus cli, including one that ignored the hydra_doc.py provided by the user
=> General config fixes on hydrus cli

cli.py, hydrus/data/crud.py, hydrus/data/exceptions.py, hydrus/resources.py, hydrus/tests/test_app.py, hydrus/utils.py
Fixes #304  
Adds various functions to provide a mechanism for pagination.
* CLI arguments to enable/disable pagination and set page size, and utility functions related to them.
* Changes in `get_collection` method in crud.py and get method of `ItemCollection` class in resources.py to implement actual pagination functionality.
* Exception class to handle excpetions related to invalid page number/id.
* Tests for pagination.
=> Add mechanism for pagination

hydrus/tests/test_app.py
Fixes #377 
Extends `test_collection_GET` to validate that the member items have valid URI.
test_collection_GET in test_app.py
=> Extend collection test to validate member item URI

examples/drones/doc.py, hydrus/samples/hydra_doc_sample.py
Fixes #
Adding DELETE to sample Drone API spec
@xadahiya was it just not necessary before or was there a specific reason to not have it?
=> Adding DELETE operation to drone collection

hydrus/auth.py, hydrus/data/exceptions.py, hydrus/resources.py, hydrus/samples/doc_writer_sample.py, hydrus/samples/doc_writer_sample_output.py, hydrus/samples/hydra_doc_sample.py, hydrus/tests/test_app.py, hydrus/tests/test_crud.py, requirements.txt
Fixes #
Returns standard response status body with help of Hydra Status and Hydra Error. Also uses them in the sample documents.
1. Avoids the use of `@id` to separate id from the message. Looking at the Spec `@id` field is supposed to point towards a detailed version of the same Status message and not towards the object on which the operation had been done.(http://www.hydra-cg.com/spec/latest/core/#description-of-http-status-codes-and-errors) So setting it to the object id would be incorrect. (We have already resolved the issue about separating id by using `Location` header value at hydra-agent to get the id of the newly created object(#392 ).
2. Linking of possibleStatus defined in ApiDoc to the statuses returned by hydrus: I tried to do this by linking this via statusCode(But it was …
=> Use HydraStatus and HydraError to return status response

hydrus/helpers.py, hydrus/resources.py, hydrus/samples/doc_writer_sample.py, hydrus/samples/doc_writer_sample_output.py, hydrus/samples/hydra_doc_sample.py, hydrus/tests/test_app.py, requirements.txt
Related to issue https://github.com/HTTP-APIs/hydra-python-core/issues/15 and PR https://github.com/HTTP-APIs/hydra-python-core/pull/28
Adapts hydrus according to changes made at core.
Adds tests for readable properties.
=> Update hydrus with latest changes made at core

hydrus/data/crud.py, hydrus/data/crud_helpers.py
Fixes #
Refactors `insert` and `insert_multiple` functions in crud.py.
Creates a new file for crud helper functions.
=> Refactor crud.insert and create new file for other crud helper functions.

hydrus/helpers.py, hydrus/resources.py, hydrus/samples/doc_writer_sample.py, hydrus/samples/doc_writer_sample_output.py, hydrus/tests/test_app.py, hydrus/tests/test_crud.py, tests/test_cli.py
Fixes #317
Extends the nested class test in test_crud.py
Refactors gen_dummy_object functions as discussed in #317
Also makes changes in helper functions to use path instead of assuming path will be equal to class_type.
=> Improve testing

hydrus/itemhelpers.py, hydrus/resources.py
related to #424
Refactored `if` conditon in resources.py.
Let me know if any thing else needs to be done.
Meanwhile, I am working on adding appropriate test cases for the changes made.
=> Refactor Item class in resources.py

cli.py, requirements.txt
Fixes #
fixes issue #451 .
1. Fixed issue with the hydrus command line utility (cli.py)
1. Changed Click version from click==6.7 to click==7.0 .
=> FIX: issue with cli.py

hydrus/auth.py, hydrus/helpers.py, hydrus/item_collection_helpers.py, hydrus/items_helpers.py, hydrus/resources.py, hydrus/utils.py
related to  #424 
Refactor `hydrus/resources.py`. This file had very poor readability and maintainability as it had all the logic for response generation and a lot of the code was repeating. I abstracted away the logic of response creation to lower level functions instead of keeping it in resources.py, thus,  increasing readability. Now resources.py only imports required helper functions(handles) instead of importing a lot of utility functions and exception classes. 
This is a big PR so these are some points on the changes I made so it becomes easier to read through the code:
* Replace the repeating authentication of request on every http method with decorator, like a *middleware*.
* move validation logic for an object before it is inserted/updated
into separate function called …
=> Refactor hydrus/resources.py

hydrus/item_collection_helpers.py
Fix `headers_` variable under POST method of Item Collection Resource.
fixes #462
Fixes #
=> Fix headers_ variable

.travis.yml, README.md, cli.py, examples/hydrus-demo-server/demo.py, hydrus/app.py, hydrus/app_factory.py, hydrus/auth.py, hydrus/conf.py, hydrus/data/crud.py, hydrus/data/crud_helpers.py, hydrus/data/db_models.py, hydrus/data/exceptions.py, hydrus/data/user.py, hydrus/helpers.py, hydrus/item_collection_helpers.py, hydrus/itemhelpers.py, hydrus/items_helpers.py, hydrus/samples/doc_writer_sample.py, hydrus/tests/test_app.py, hydrus/tests/test_auth.py, hydrus/tests/test_crud.py, tests/test_pep8.py
related to #424 
* refactor error responses with `error_response` function
* refactor validation logic of objects while inserting / updating using `validate_object` function
* replace  `.format(...)` strings with Python 3.6+'s "f-strings" in the whole hydrus codebase. Not only are f-strings more readable, more concise, and less prone to error than other ways of formatting, but they are also faster.
=> Refactor hydrus

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
Update them with the info that hydrus only supports python version >= 3.6.0
=> Update contributing.md and PR template

Dockerfile, cli.py
Fixes #470 
`--use-db` option to use a database created by previous hydrus instances.
`python cli.py serve --use-db`
=> Added cli option to use existing database

examples/drones/doc.py, examples/drones/doc_gen.py
The code was using the old hydrus api. Updated it.
Fixes #454
=> Regenerate the examples/drones/doc.py

hydrus/data/crud.py, hydrus/data/crud_helpers.py
Related to #424 
Refactor parts of `hydrus/data/curd.py`.
=> Refactor crud.py

Dockerfile
@xadahiya had requested to update the `hydrus` docker image to update the docker image to use https://github.com/tiangolo/uwsgi-nginx-flask-docker(python 3.7).
=> Update Docker image to use python 3.7

examples/drones/doc.py, examples/drones/doc_gen.py, hydrus/samples/doc_writer_sample_output.py, hydrus/samples/hydra_doc_sample.py
Fixes #482 
According to the latest changes in the core library, this PR updates the sample docs used throughout and also the sample code used to generate the sample docs. 
- Updated Dones Doc
- Update sample doc by doc_writer
- code to generate doc by doc_writer
=> Update sample docs

hydrus/app.py, hydrus/data/doc_parse.py
* Remove unwanted `insert_classes` function which was causing build failure when `hydrus` is launched through docker.
=> FIX: failing docker build

hydrus/data/crud.py, hydrus/data/db_models.py, hydrus/data/resource_based_classes.py, hydrus/helpers.py, hydrus/item_collection_helpers.py, hydrus/itemhelpers.py, hydrus/tests/conftest.py
Fixes #489
Now, collections support instances of different classes as members. :rocket:
1) **PUT** on `/collection/`
The request body should have the list of `@id`s of class instances which would be grouped into a collection.
**NOTE: These instances should exist in the database before grouping them into a collection.**
For eg,
```json
{
"@type": "LogEntryCollection",
"members": [
{
"@id": "/serverapi/Drone/4ff14a9e-9cd0-4e8a-9c11-86ac9bec211f",
"@type": "Drone"
},
{
"@id": "/serverapi/LogEntry/aab38f9d-516a-4bb2-ae16-068c0c5345bd",
"@type": "LogEntry"
}
]
}
```
In the above example, a `LogEntry` instance with id(primary key) 'aab38f9d-516a-4bb2-ae16-068c0c5345bd' and a `Drone` instance with id(primary key) '4ff14a9e-9cd0-4e8a-9c11-86ac9bec211f' already exist in the database.
This adds …
=> Add support for multiple resource type collections

hydrus/data/crud.py, hydrus/helpers.py, hydrus/item_collection_helpers.py, hydrus/itemhelpers.py, hydrus/tests/functional/test_app.py
* previously(PR #488 ) `/class` endpoint served all the members of class, now made `/collection` endpoint to serve all members of class.
* `/class` endpoint still used for adding class members.(**PUT**)
* **GET** on `/class` endpoint gives `405` status code.
=> Rectify GET on /collection endpoint

setup.py
Fixes #499 
This PR brings the setup.py file to support the latest version of pip. Earlier pip versions>=20 were not supported.
* Support for pip >= 20
=> Update setup.py file to reflect latest pip upgrade

setup.py
=> update setup.py file to reflect latest pip upgrade (#500)

examples/drones/doc.py, examples/drones/doc_gen.py, hydrus/samples/hydra_doc_sample.py
Fixes #501 
Added the dronecollection as a supported collection in the doc_gen.py file and replaced the old sample docs by the new one generated. 
Fixed missing dronecollection by replacing the extra messagecollection.
=> Dronecollection

examples/drones/doc.py, examples/drones/doc_gen.py, hydrus/samples/hydra_doc_sample.py
This reverts commit 27b0c3612165ab566c54d8b8912ad00b250326bc.
Fixes #
Reverting Changes from master as it should have been merged in the develop
=> Revert #511 (Add missing drone collection in sample API DOC)

examples/drones/doc.py, examples/drones/doc_gen.py, hydrus/samples/hydra_doc_sample.py
Fixes #501 , #509 
Add missing Drone Collection in the sample API DOC.
=> Add missing drone collection in API DOC

README.md, cli.py, docker-compose.yml, examples/drones/doc.py, examples/drones/doc_gen.py, hydrus/app.py, hydrus/samples/hydra_doc_sample.py, poetry.lock, pyproject.toml, requirements.txt, setup.cfg, setup.py
=> Align master to develop

.github/ISSUE_TEMPLATE.md
Fixes #536
Snapshot field added to the ISSUE_TEMPLATE.md
=> Snapshot field added.

hydrus/tests/functional/test_auth.py
Fixes #544 
The endpoints return a json with` '@context', '@id', '@type', 'anotherSingleClass', 'collections', 'dummyClass', 'singleClass'` and collection_names returns the a list of two collections `['Extraclasses', 'dummyclasses']` . The **if** condition was never met and rest of the code including **assert** statements was not being executed. 
Used endpoints["collections"] to get 'id' of every collection and get a response from test_client and check correct status_code.
**Tests changed:**
- test_wrong_id_get
- test_wrong_pass_get
- test_wrong_nonce_get
- test_correct_auth_get
=> Fixed some tests in test_auth.py

hydrus/app.py
Fixes #549 
Added `scoketio.run(app)` instead of `app.run()` using `create_socket` method available in socket_factory.py.
`app.run()` to `scoketio.run(app)`
=> POST & DELETE request error fixed.
