hydrus/app.py
hydrus/data/db_models.py
hydrus/data/exceptions.py
hydrus/data/user.py
hydrus/tests/test_auth.py
hydrus/utils.py
main.py
requirements.txt

- Using new greenlet based Python servers. Fixes the problem of dev servers freezing randomly.
- Adding functions for authorization.
- Using HTTP Basic Authorization, using the Authorization Header in the request. 
- User ID and Password hash encrypted in base64 separated by a colon (:) as per the HTTP standard.
[https://tools.ietf.org/html/rfc7617](https://tools.ietf.org/html/rfc7617)
Todo:
- Need to implement secure TLS communication for the server. Otherwise, the hash may be replicated.
- Implement handshaking between server and client for better security.

Using greenlet based servers and authorization

---

hydrus/tests/test_auth.py

The following commits fixed the `test_auth.py` module by changing the encoding structure of authentication string to `b64encode`

Fixed authentication tests

---

hydrus/app.py

Fixes #122 
The following commits fix the behaviour of status codes returned by the hydrus server for non existing collections.
NOTE - I didn't knew how to log tests, so posting a picture of the test runs. Please guide me on that.
The server initially returned status code 405 for any random url of form `/API_NAME/randomwords`.
The new `check_endpoint` function now provides a `status code 404` for collections not existing in the database. New response attatched below:

Fix status code response

---

cli.py

Closes https://github.com/HTTP-APIs/hydrus/issues/160
Add option for setting database URL and server URL in hydrus CLI

Add CLI option to add database and server url

---

hydrus/app.py
hydrus/data/db_models.py
hydrus/data/user.py
hydrus/tests/test_auth.py
hydrus/utils.py
main.py

Fixes #123 #120 
These changes allow an authenticated user to get a token after authenticating with the server and the token allows the user to access the protected resources of the API by using the token in the url as:
`http:localhost:8080/serverapi/SomeCollection?token="API_TOKEN"` without authorizing itself.
Also this fixes the repetition of code in `app.py` module by combining the authentication steps in on e function #120 (tested the server on browser)
1. The user authenticates itself with the server using username and password.
2. After succesful authentication, the server responds with a server token for further use
3. This token can then be used to directly acces the protected endpoints from any source.
NOTE:
1. For now the server issued tokens are generated for infinite time, …

Added token based authentication feature for user

---

hydrus/parser/openapi_parser.py
hydrus/samples/hydra_doc_sample.py

Fixes #211
The parser can now go to any level deep to parse class or other objects .Earlier we were only able to go 1 level deep now we are parsing iteratively to fetch data.

Parsing  the class location iteratively 

---

hydrus/parser/openapi_parser.py
hydrus/samples/hydra_doc_sample.py

Fixes #213 
- [X ] My branch is up-to-date with upstream/develop branch.
- [X ] Everything works and tested for Python 3.5.2 and above.
All the classes/ definitions that have been parsed will be added .

removed conditions restricting addition of only classes with paths

---

hydrus/parser/openapi_parser.py
hydrus/samples/hydra_doc_sample.py

Fixes #238 and #237 
Fixed extra '/' in the URL and extra endpoints in the entrypoint

Fixed extra '/' and extra paths in the URL 

---

hydrus/parser/openapi_parser.py
hydrus/samples/hydra_doc_sample.py

- [ X] My branch is up-to-date with upstream/develop branch.
- [X ] Everything works and tested for Python 3.5.2 and above.
i did not push the latest change to the previous PR #241 , this one has the correct if condition for updating the endpoint param .

Wrong condition in parser 

---

hydrus/hydraspec/doc_writer.py
hydrus/samples/doc_writer_sample_output.py

Fixes #245 
We had an extra "_:" in every doc , we removed that in this PR .
```
"supportedOperation": [
{
"@id": "_:_:httpapilog_collection_retrieve",
"@type": "hydra:Operation",
"description": "Retrieves all HttpApiLog entities",
"expects": "null",
"method": "GET",
"returns": "vocab:HttpApiLogCollection",
"statusCodes": []
},
{
"@id": "_:_:httpapilog_create",
"@type": "http://schema.org/AddAction",
"description": "Create new HttpApiLog entitity",
"expects": "vocab:HttpApiLog",
"method": "PUT",
"returns": "vocab:HttpApiLog",
"statusCodes": [
{
"description": "If the HttpApiLog entity was created successfully.",
"statusCode": 201
}
]
}
```

fixed extra _: issue

---

hydrus/parser/openapi_parser.py

Fixes #280 
Test logs:
```shell
(venv) usman@lenovo:~/OpenSource/hydrus^pep8-fix ♥
$ python -m unittest hydrus/tests/test_parser.py                            11/19/18 -  8:30 AM
Importing Open Api Documentation ..
......Method on path/pet/findByStatus already present !
Method on path/pet/findByTags already present !
Method on path/pet/{petId} already present !
Cannot parse path/pet/{petId} because no ref to local class provided
Cannot parse path/pet/{petId} because no ref to local class provided
Cannot parse path/store/inventory because no ref to local class provided
Cannot parse path/store/order/{orderId} because no ref to local class provided
Method on path/user/createWithArray already present !
Method on path/user/createWithList already present !
Cannot parse path/user/login because …
```

Fixed pep8 for openapi_parser.py

---

hydrus/samples/doc_writer_sample.py
hydrus/samples/doc_writer_sample_output.py
hydrus/tests/test_app.py

Fixes #296 
Adapts the tests in test_app.py to recent changes.
```
(h) vishal@vishal:~/oss/hydrus$ pytest hydrus/tests/
============================================================ test session starts ============================================================
platform linux -- Python 3.5.2, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/vishal/oss/hydrus, inifile:
collected 51 items                                                                                                                          
hydrus/tests/test_app.py ................                                                                                             [ 31%]
hydrus/tests/test_auth.py ..........                                                                                                  [ 50%] …
```

Adapt and modify tests

---

hydrus/data/db_models.py
hydrus/data/user.py

Fixes #178
- The PR adds a `expiry` field to Token with an expiration time of 2700 seconds and makes the necessary changes in the dependent functions.
- A possible addition could be adding an option in the `cli` to set the expiration time manually.
Although, the best approach here should be using JWT which encodes user info, coupled with redis, since using a RDBMS would unintentionally add write overhead.
```
========================== test session starts ===========================
platform linux -- Python 3.6.7, pytest-4.0.2, py-1.7.0, pluggy-0.8.0
rootdir: /home/invinciblycool/Documents/Github-projects/hydrus, inifile:
collected 51 items                                                       
hydrus/tests/test_app.py ................                          [ 31%] …
```

Add expiry field to Token

---

hydrus/parser/openapi_parser.py
hydrus/samples/doc_writer_sample.py

Fixes #343 
Currently, file handling is done without `with` keyword, which in fact is dangerous because if an exception occurs before the call to `close()` then `close()` will not be called and the memory issues can occur, or the file can be corrupted.
Used `with` to open files in place of directly calling `open()` function.

Add 'with' keyword for file I/O

---

hydrus/data/crud.py
hydrus/helpers.py
hydrus/parser/openapi_parser.py
hydrus/resources.py

Some placeholders within str.format() expression were found missing and have been properly placed.
Fixes #303 and is directly on master to fix a bug created in a merged commit.
This PR is to solve an issue that was brought in due to the lack of placeholders within the str.format() function calls in the resources.py file.
Fix missing {} placeholders within str.format() expressions.

FIX: placeholders found missing, placed properly

---

requirements.txt

Fixes #
When I tried to build and run the docker image, I got the following error:
ImportError: No module named 'hydra_python_core'
To solve it, is just change the installation of the hydra_python_core and the hydra_openapi_parser.
Edit the lines on requirements.txt that install the hydra dependences

Solving requeriments problems

---

cli.py
tests/test_pep8.py

Fixes parts of #361
I have moved the tests out of the module and made changes to the cli interface. Grammatical in nature as well.
Test for PEP8 compliance moved out of `hydrus/`. It also ignores the files with `examples`, but this can changed as required. Side Note: `examples/` have a lot of non-compliant code. My reasoning behind is this is that Hydrus' CLI script doesn't come under the ambit of the test_pep8.py as implemented now.

Rewrite cli.py and move tests into repo root

---

requirements.txt

Fix vulnerabilities in some libraries.
@xadahiya @chrizandr please fix the versions in demos running in the cloud.
**It is an anti-pattern to pin all the requirements. Pinned requirements shall be kept to minimal.**
Some cases to keep a library pinned:
* unstable API
* not security-related/injection-prone

Remove restrictions to libraries version

---

hydrus/data/crud.py
hydrus/tests/test_crud.py

Fixes #375 
Added test for nested objects
Adapt tests to use UUIDs
Corrected mypy type annotation in crud.py

Add crud test for nested objects

---

hydrus/data/crud.py
hydrus/data/exceptions.py
hydrus/helpers.py
hydrus/resources.py
hydrus/tests/test_app.py
hydrus/tests/test_crud.py

Fixes #302 
Add searching mechanism to hydrus with help of IriTemplate.
Added functions in helpers.py to generate IriTemplate for collections.
Added functions in crud.py to filter collections according to search parameters.
It pretty much (or maybe completely) follows the procedure mentioned in the spec. To test it 
1) Dereference any Collection endpoint(DroneCollection for example).
2) The response will contain IriTemplate attached to the search property.
3) The IriTemplate will have different IriTemplateMapping for each variable. You can use any combination of these variables to search the collection. (To name nested properties we follow a simple convention. They are represented as `PropertyTitle[NestedPropertyTitle]`, so the variable to search drones by speed would be named as …

Implement search mechanism

---

hydrus/data/crud.py
hydrus/data/exceptions.py
hydrus/helpers.py
hydrus/resources.py
hydrus/tests/test_app.py
hydrus/tests/test_crud.py
tests/test_cli.py
tests/test_pep8.py

Fixes #302 
Refactors some old code and provides clients way to control pagination parameters `pageIndex`, `limit` and `offset`.

Add mechanism to support client-controlled pagination

---

hydrus/data/crud.py
hydrus/helpers.py
hydrus/resources.py
hydrus/samples/doc_writer_sample.py
hydrus/samples/doc_writer_sample_output.py
hydrus/samples/hydra_doc_sample.py
hydrus/tests/test_app.py
hydrus/tests/test_crud.py
requirements.txt
tests/test_cli.py

Fixes https://github.com/HTTP-APIs/hydra-python-core/issues/30
Extends and improves the handling of nested class properties with the help of HydraLink.
Work in progress
Issue: Adding Link properties as GraphIII triples instead of GraphIIT triples.
Currently, it uses regex to identify links, extracts id of the nested resource and adds a GraphIII triple. I am looking for a more robust solution, I'll try out passing a list of Link properties to `crud.insert` and add a function to add GraphIII triples for GraphIII relationships defined with the help of links, so we can avoid regex and be sure about proper handling of such GraphIII relations expressed as link.
Also, need to adapt tests.

Use HydraLink to improve handling of nested class properties

---

examples/drones/doc.py
hydrus/data/crud.py
hydrus/data/crud_helpers.py
hydrus/tests/test_app.py

Fixes #429.
* Add context to the following properties: `totalItems`, `view`, `first`, `last` by prefixing them with `hydra`.
* Regenerated the API documentation of the hydrus demo after fixing the incomplete contexts.
* Fix tests appropriately for the changes made.
NOTE: This PR complements https://github.com/HTTP-APIs/hydra-python-core/pull/34.

FIX: incomplete contexts in hydrus demo

---

cli.py
hydrus/conf.py

Fixes #446, #442 
This PR enables cli.py file to first check into environment variable before falling back onto sample hydradoc. Initially, when the cli arguement hydradoc was not passed, it used the sample hydradoc. Now it searches the environment variables, if found it uses it, if not it uses the sample hydradoc. 
Ability to check into environment variables first before using sample hydradoc. 
Use of hydradoc from environment variables.

check in environment variables before falling back to sample doc

---

requirements.txt

Fixes #457
This PR updates the MarkupSafe version from 1.0 to 1.1.1, to avoid error. Earlier it was 1.0. Now its updated to 1.1.1
Update MarkupSafe to 1.1.1
Updated MarkupSafe from version 1.0 to 1.1.1
Earlier creating docker image threw error. Now its building fine.

change MarkupSafe version from 1.0 to 1.1.1

---

hydrus/item_collection_helpers.py

related to #424 
Migrates the string formatting to use f string. This was the last instance of old `.format` string formatting in the whole codebase.
I couldn't do this change in [this](https://github.com/HTTP-APIs/hydrus/pull/461) PR as this format string had gone a [recent change](https://github.com/HTTP-APIs/hydrus/pull/463) in `develop` on to which I didn't want to rebase my commits of [this](https://github.com/HTTP-APIs/hydrus/pull/461) PR

Convert format string to f string

---

Dockerfile

Fixes #473
Using the previous base image, `tiangolo/uwsgi-nginx-flask`, gave
error server certificate verification.
Refer https://github.com/tiangolo/uwsgi-nginx-flask-docker/issues/181 for more details.
Also, switched base image from python3.8 to python3.6 as psycopg2 as error on building
on python3.8.
Refer https://github.com/psycopg/psycopg2/issues/858 for more details.

FIX: docker-compose was failing with SSL error

---

docker-compose.yml

Fixes #475
Made the default PORT and API_NAME same for both the cases,
when hydrus is started from `hydrus serve` as well
`docker-compose up --build`.
Now default PORT is **8080** and API_NAME is **serverapi**

MANIT: Make the defaults same

---

cli.py
hydrus/data/crud.py
hydrus/data/crud_helpers.py
hydrus/data/db_models.py
hydrus/data/doc_parse.py
hydrus/data/exceptions.py
hydrus/data/resource_based_classes.py
hydrus/item_collection_helpers.py
hydrus/itemhelpers.py
hydrus/items_helpers.py
hydrus/tests/conftest.py
hydrus/tests/functional/test_app.py
hydrus/tests/unit/test_crud.py

Related #412 
I have wrote POC code for making the database tables from parsing the API Doc.
This makes a table for each `hydra:Resource` (Classes and Collections both).
At the moment, the database schema is just a table for each resource.
The columns in each table are its all the properties in that classes / collection's `supportedProperty`.
Right now, I have just defined all these columns using the `STRING` class from sqlachemy.
There is also, a `id` column in each table acting as a primary key.
The database schema looks like, 
(I have attached the schema in the form of the SQL commands used to make that table, will update it with a proper visual schema. I did not find a tool to convert my `.db` file, to a visual schema.)

Make db tables for each resource in apidoc

---

hydrus/data/crud.py
hydrus/item_collection_helpers.py
hydrus/itemhelpers.py

Fixes #481 
In a lot of places, `hydrus` assumed that collections could only be "[classname]Collection".
Removed this explicit dependency on this notation.

Better discover collections

---

hydrus/data/crud.py
hydrus/helpers.py
hydrus/item_collection_helpers.py

Fixes #485 
- This PR removes the error thrown on making GET request on Collection endpoints when started via cli with --no-pagination flag. 
- As we have discussed earlier, the wrong template was returned. So one minor change this PR does is that replaces parentheses by curly braces and add ? symbol to indicate key-value pairs are accepted. Ref: https://tools.ietf.org/id/draft-gregorio-uritemplate-08.html#rfc.section.3.2.8
- Curly braces instead of paranthesis
- Maximum possible number of members in non-paginated collection

correct  template and fix no-pagination

---

cli.py
examples/hydrus-demo-server/demo.py
hydrus/app.py
hydrus/app_factory.py
hydrus/data/db_models.py
hydrus/data/doc_parse.py
hydrus/helpers.py
hydrus/items_helpers.py
hydrus/samples/doc_writer_sample.py
hydrus/samples/doc_writer_sample_output.py
hydrus/samples/hydra_doc_sample.py
hydrus/tests/conftest.py
hydrus/tests/functional/test_app.py
hydrus/tests/functional/test_socket.py
hydrus/tests/unit/test_crud.py

Fixes #482 
`hydrus` depended on the `vocab` keyword in a lot of places for essential operations like identifying foreign key relationships, etc.
This was not ideal behaviour.
After support for expanded API DOCs was added in `hydra-python-core` repo in PR https://github.com/HTTP-APIs/hydra-python-core/pull/42, the core library now returns an expanded APIDOC.
So, in this PR, added support for expanded API DOC.
**Note:** The build is failing currently due to some minor bugs in the core repo which @priyanshunayan is currently fixing.

Remove hardcoded dependencies on vocab keyword

---

README.md
docker-compose.yml

Fixes #519 
The port number is now fixed in the read me which previously showed 8000. 
the startup demo now serves at `http://localhost:8080/api/vocab`

Fixed Port Number in README and the startup demo now serves at api/

---

poetry.lock
pyproject.toml
requirements.txt

Fixes #530 
Update psycopg2 to version 2.8.6 which now supports python3.8
update requirements.txt and poetry files for error-free install using either of methods in python v3.8
dependencies weren't able to install because of incompatibility of psycopg2 and python3.8 now works with python3.8 after bump

Python 3.8 support 

---

hydrus/conf.py

Fixes #540 
**hydrus/conf.py**'s function _get_apidoc_path()_ first checks for APIDOC_REL_PATH path in environment variables. Currently it gives error if we'll try to run hydrus after specifying the path of jsonld or yaml file in environment variable. It's because some required modules are were not imported.
imported json,yaml and parse function from hydra_openapi_parser

added hydrus/conf.py required imports

---

Dockerfile

maintainer depreacted for LABEL
Fixes #535 
[Reference](https://apimirror.com/docker~19/engine/deprecated/index) 
MAINTAINER was deprecated in v1.13.0 instead of it use of LABEL.
DockerFile Maintainer to LABEL
MAINTAINER Key from docker File

chore: docker file deprication

---

hydrus/conf.py
hydrus/data/crud.py
hydrus/data/crud_helpers.py
hydrus/helpers.py
hydrus/tests/functional/test_app.py

Fixes #507
Related to [this PR](https://github.com/HTTP-APIs/hydrus/pull/527)
All paths starting with `/...` are changed with `http://localhost:8000/...` so that the link can be followed by clicking/reading/dereferencing the string. I have created a get_host_domain function to get the localhost and port. Please let me know if this isn't the right approach.
-  Added get_host_domain function in _conf.py_
- Changed f-strings to get new links.
- added get_host_domain()
New Output at ```http://localhost:8080/serverapi/DatastreamCollection```:
```
{
"@context": "http://localhost:8080/serverapi/contexts/DatastreamCollection.jsonld",
"@id": "http://localhost:8080/serverapi/DatastreamCollection/",
"@type": "DatastreamCollection",
"hydra:totalItems": 0,
"hydra:view": {
"@id": …
```

Added domain name for IRI in the API

---

hydrus/data/crud.py
hydrus/helpers.py

Fixes #507 
I missed these changes in previous PR, let me know if anything else is missing.
The domain name is missing in the `@id` field when making a GET request to `http://localhost:8080/serverapi/<resource_name>/<id>`. _Originally posted in https://github.com/HTTP-APIs/hydrus/issues/507#issuecomment-766796234_
New Response for GET :  `/<class_endpoint>/<id>`
```
{
"@context": "http://localhost:8080/serverapi/contexts/Movie.jsonld",
"@id": "http://localhost:8080/serverapi/Movie/01169a02-66b3-41c5-a3c9-e35d7d309e21",
"@type": "Movie",
"movie_director": "Todd Phillips",
"movie_name": "Hangover"
}
```
For GET : `/<collection_endpoint>/<id>`
```
{
"@context": "http://localhost:8080/serverapi/contexts/MovieCollection.jsonld",
"@id": …
```

Added full domain for CRUD 

---

hydrus/data/db_models.py
hydrus/data/resource_based_classes.py
hydrus/tests/functional/test_app.py

Fixes #555
- Previously,  a member with the same ID can be added multiple times in the same collection.
- Member ID in Collection database table is changed to a unique key and hydrus handles the integrity error and raises InstanceExists error if an object with existing ID is inserted in a collection. A response with 400 (Bad Request) code is returned.
```
{
"@context": "http://www.w3.org/ns/hydra/context.jsonld",
"@type": "Error",
"description": "Instance of type Movie with ID c1b62361-e9c6-4185-b496-b74dff4fb8a4 already exists",
"statusCode": 400,
"title": "Instance already exists."
}
```

Unique constraint for member ID in collections
